### ISSUE TITLE
`table.transform()` should preserve `rowid` values

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#592]
I just spotted a bug when using https://datasette.io/plugins/datasette-configure-fts and https://datasette.io/plugins/datasette-edit-schema at the same time.

Steps to reproduce:

- Configure FTS for a table, then run a test search
- Edit the schema for that table and change the order of columns
- Run the test search again

I got the wrong search results, which I think is because the `_fts` table pointed to the first table by `rowid` but those `rowid` values were entirely rewritten as a consequence of running `table.transform()` on the table.

Reconfiguring FTS on the table fixed the problem.

I think `table.transform()` should be able to preserve `rowid` values.

**Comment by simonw** [comment]
That's odd, I wrote a test for this just now and it passes already:
```python
def test_transform_preserves_rowids(fresh_db):
    # Create a rowid table
    fresh_db["places"].insert_all(
        (
            {"name": "Paris", "country": "France"},
            {"name": "London", "country": "UK"},
            {"name": "New York", "country": "USA"},
        ),
    )
    assert fresh_db["places"].use_rowid
    previous_rows = list(
        tuple(row) for row in fresh_db.execute("select rowid, name from places")
    )
    # Transform it
    fresh_db["places"].transform(column_order=("country", "name"))
    # Should be the same
    next_rows = list(
        tuple(row) for row in fresh_db.execute("select rowid, name from places")
    )
    assert previous_rows == next_rows
```
So maybe I'm wrong about the cause of that bug?

**Comment by simonw** [comment]
I tried bumping that up to 10,000 rows instead of just 3 but the test still passed.

**Comment by simonw** [comment]
I just noticed that the table where I encountered this bug wasn't actually a `rowid` table after all - it had an `id` column that was a text primary key.

The reason the `rowid` was important is that's how the FTS mechanism in Datasette relates FTS entries to their rows.

But I tried this test and it passed, too:
```python
def test_transform_preserves_rowids(fresh_db):
    fresh_db["places"].insert_all(
        [
            {"id": "1", "name": "Paris", "country": "France"},
            {"id": "2", "name": "London", "country": "UK"},
            {"id": "3", "name": "New York", "country": "USA"},
        ],
        pk="id",
    )
    previous_rows = list(
        tuple(row) for row in fresh_db.execute("select rowid, id, name from places")
    )
    # Transform it
    fresh_db["places"].transform(column_order=("country", "name"))
    # Should be the same
    next_rows = list(
        tuple(row) for row in fresh_db.execute("select rowid, id, name from places")
    )
    assert previous_rows == next_rows
```

**Comment by simonw** [comment]
Oh! Maybe the row ID preservation here is a coincidence because the tables are created from scratch and count 1, 2, 3.

If I delete a row from the table and then insert some more - breaking the `rowid` sequence - it might show the bug.

**Comment by simonw** [comment]
Yes! That recreated the bug:
```
>       assert previous_rows == next_rows
E       AssertionError: assert equals failed
E         [                                                                [                                                               
E           (1, '1', 'Paris'),                                               (1, '1', 'Paris'),                                            
E           (3, '3', 'New York'),                                            (2, '3', 'New York'),                                         
E           (4, '4', 'London'),                                              (3, '4', 'London'),                                           
E         ]                                                       ...
E         
```

**Comment by simonw** [comment]
In working on this I learned that `rowid` values in SQLite are way less stable than I had thought - in particular, they are often entirely rewritten on a `VACUUM`:

https://www.sqlite.org/lang_vacuum.html#how_vacuum_works

> The VACUUM command may change the [ROWIDs](https://www.sqlite.org/lang_createtable.html#rowid) of entries in any tables that do not have an explicit [INTEGER PRIMARY KEY](https://www.sqlite.org/lang_createtable.html#rowid).

So this fix wasn't as valuable as I thought. I need to move away from ever assuming that a `rowid` is a useful foreign key for anything.

**Comment by Thangaraj-Ideas2it** [comment]
## anticlock — issue analysis

**Root cause:** table.transform_sql rebuilds the table without preserving implicit rowid, causing FTS rowid mappings to break after transform()

**Affected files:**
- `sqlite-utils/sqlite_utils/db.py`

### Analysis

transform_sql creates a new table and copies data with an INSERT ... SELECT that only copies ordinary columns derived from PRAGMA table_info (columns_dict). Because PRAGMA table_info does not list the implicit rowid, transform_sql does not include rowid in the copy and SQLite assigns new rowids for the new table. FTS virtual tables and the FTS triggers rely on the original table.rowid (populate_fts and enable_fts use/insert rowid), so the rowid→row mapping used by FTS becomes incorrect after transform().
--repo is not a git repository; patch.diff is empty and changed_files is unavailable

**Comment by Thangaraj-Ideas2it** [comment]
## anticlock — issue analysis

**Root cause:** table.transform() does not preserve rowid when recreating a table, so FTS indexes (which reference rows by rowid) become misaligned.

**Affected files:**
- `sqlite-utils/sqlite_utils/db.py`

### Analysis

Root cause: transform_sql() builds a copy SQL that INSERTs only the table columns into the new table and does not preserve the original rowid for tables that use rowid as the primary key. The copy statement is:
  INSERT INTO [new_table] (cols) SELECT old_cols FROM [old_table];
Because rowid is not selected and inserted, SQLite assigns new rowid values in the recreated table. FTS virtual tables and triggers store row mapping by rowid (populate_fts() selects rowid and FTS triggers use new.rowid/old.rowid), so after transform the FTS index points to different rows.

What I inspected (source-grounded evidence below) shows transform_sql() creating the new table and the copy SQL without preserving rowid, and populate_fts()/enable_fts() relying on rowid for FTS mapping. A fix would update transform_sql() to preserve rowid when the original table uses rowid (e.g. include rowid in the SELECT/INSERT and, when creating a table with an explicit primary key, copy rowid into the new integer primary key column).

--repo is not a git repository; patch.diff is empty and changed_files is unavailable

**Comment by Thangaraj-Ideas2it** [comment]
## anticlock — issue analysis

**Root cause:** Table.transform_sql does not preserve implicit rowids when rebuilding a table: the INSERT INTO ... SELECT copy omits rowid so new rowids are assigned, breaking FTS which references rows by rowid.

**Affected files:**
- `sqlite-utils/sqlite_utils/db.py`

### Analysis

Root cause: In Table.transform_sql (sqlite-utils/sqlite_utils/db.py) the code builds copy_from_to from self.columns_dict (which reflects PRAGMA table_info and therefore does not include the implicit rowid). It then generates a copy SQL of the form "INSERT INTO [new_table] (col1, col2...) SELECT col1, col2... FROM [old_table];" (no rowid column). For tables that rely on implicit rowid (no explicit PK), this causes new rowids to be assigned in the new table, shifting rowid→row mapping. FTS virtual tables store content keyed by rowid, so after transform the FTS index points at the wrong rows.

Source-grounded evidence:
- sqlite-utils/sqlite_utils/db.py:1360-1370 — columns property: PRAGMA table_info is used to enumerate columns. This demonstrates columns_dict will not include the implicit rowid, so transform cannot see rowid here (lines 1360-1370).
- sqlite-utils/sqlite_utils/db.py:1842-1852 — transform_sql constructs copy_from_to from self.columns_dict (line 1844) and maps old->new column names. This shows the copy mapping only includes real columns, not rowid.
- sqlite-utils/sqlite_utils/db.py:1917-1920 — transform_sql builds copy_sql as "INSERT INTO [new_table] ({new_cols}) SELECT {old_cols} FROM [{old_table}];" (no rowid). This is the specific line where rowid preservation would need to be handled; as written it omits rowid so new rowids are generated.

Impacted file(s):
- sqlite-utils/sqlite_utils/db.py (primary fix location)

What a fix would touch: alter Table.transform_sql to detect when the original table uses implicit rowid (no explicit primary key), and when appropriate include "rowid" in the copy_from_to / copy_sql so that the INSERT copies rowid explicitly (INSERT INTO new_table(rowid, col...) SELECT rowid, col... FROM old_table), preserving ids and keeping FTS mappings valid. Tests exercising transform with FTS should also be added/updated.

Detailed reasoning:
- The PRAGMA table_info used by columns and columns_dict omits the implicit rowid column; transform_sql only operates over columns_dict.
- When transforming a table without explicit PK, the new table is created without explicit PK and the copy SQL then inserts rows without specifying rowid, so SQLite assigns new rowids in insertion order.
- FTS virtual tables refer to table rows by rowid; if rowids change, the FTS table contains entries pointing to old rowids which now refer to different rows (or no rows), producing incorrect search results.

Therefore the root cause is the omission of rowid in the copy operation in Table.transform_sql (sqlite-utils/sqlite_utils/db.py), at the INSERT/SELECT construction around line 1919.
--repo is not a git repository; patch.diff is empty and changed_files is unavailable

**Comment by Thangaraj-Ideas2it** [comment]
## anticlock — issue analysis

**Root cause:** transform_sql omits copying rowid when recreating a rowid table, causing rowid remapping and breaking FTS links

**Affected files:**
- `sqlite-utils/sqlite_utils/db.py`

### Analysis

Analysis

I inspected the Table.transform()/transform_sql() implementation in sqlite-utils and the FTS code that populates the FTS virtual table. The transform implementation creates a new table and copies data with an INSERT INTO new_table (col1, col2...) SELECT col1, col2... FROM old_table. That copy logic builds its column list from self.columns_dict (the declared columns) and therefore omits the implicit rowid for tables that use rowid (no explicit PK). When the new table is created as a rowid table (no explicit primary key), SQLite assigns new rowids for the inserted rows rather than preserving the original rowids. FTS virtual tables store references to rows by rowid, so after transform the FTS index points to the wrong rows until the FTS is rebuilt.

Root cause (source-grounded)

- The root cause is in sqlite-utils/sqlite_utils/db.py in the Table.transform_sql method: the initial copy mapping is built from the table's declared columns only, via copy_from_to = {column: column for column, _ in current_column_pairs} (this excludes the implicit rowid). Because rowid is not included in the INSERT/SELECT, the new table receives new rowid values.

Why this breaks FTS

- The FTS implementation stores entries using the table rowids (populate_fts uses SELECT rowid, {columns} FROM [{table}]). If transform recreates the table without preserving rowid values, the FTS index rows still refer to the old rowid numbers, which now map to different data rows. That produces the user-observed wrong search results until FTS is reconfigured/repopulated.

Evidence (confirmed in source)

- sqlite-utils/sqlite_utils/db.py:1844 — copy_from_to = {column: column for column, _ in current_column_pairs}
  - This is where the mapping of columns to copy is initialized from declared columns; implicitly excludes rowid because rowid is not a declared column.

- sqlite-utils/sqlite_utils/db.py:1920-1925 — construction of copy_sql:
  - "INSERT INTO [{new_table}] ({new_cols})\n   SELECT {old_cols} FROM [{old_table}];"
  - This shows the actual copy statement uses only the listed columns (new_cols/old_cols) and therefore does not copy rowid when it wasn't included in copy_from_to.

- sqlite-utils/sqlite_utils/db.py:2439-2441 — populate_fts():
  - "INSERT INTO [{table}_fts] (rowid, {columns})\n                SELECT rowid, {columns} FROM [{table}];"
  - This shows FTS stores entries by rowid. If the table's rowids change, the FTS index will point to wrong rows.

Affected files (would be touched by a fix)

- sqlite-utils/sqlite_utils/db.py — transform_sql (and possibly related transform logic and tests)

Suggested fix (not applied here)

- When transforming a table that uses rowid (Table.use_rowid is True / no explicit PK), include rowid in the copy mapping and in the INSERT/SELECT so the original rowid values are preserved in the new table. For example, prepend 'rowid' to old_cols/new_cols when self.use_rowid is True. This preserves FTS rowid references.

Conclusion

The transform implementation fails to preserve implicit rowid values when recreating a table without an explicit primary key. That causes FTS virtual tables (which point to rows by rowid) to become inconsistent after transform. The bug is in Table.transform_sql in sqlite-utils/sqlite_utils/db.py (around line 1844 and the later copy_sql construction at ~1920).
--repo is not a git repository; patch.diff is empty and changed_files is unavailable

**Comment by Thangaraj-Ideas2it** [comment]
## anticlock — issue analysis

**Root cause:** transform_sql creates and populates a new table using INSERT ... SELECT without preserving rowid, so transform() ends up reassigning rowids and breaking FTS rowid-based mappings.

### Analysis

Candidate (only one): sqlite-utils/sqlite_utils/db.py: transform (declared lines 1690-1755)

What I inspected:
- transform() (lines ~1732-1755) calls self.transform_sql(...) to produce a sequence of SQL statements and then executes them inside a transaction: "for sql in sqls: self.db.execute(sql)" (lines 1752-1754). This shows transform() runs the SQL produced by transform_sql.
- transform_sql() builds a new table (create_table_sql) and then builds a copy SQL at line 1920: the INSERT INTO [{new_table}] ({new_cols}) SELECT {old_cols} FROM [{old_table}]; and appends that SQL to the list (line 1926). That INSERT copies the content but does not copy or specify the original rowid column.

Why this causes the reported symptom:
- FTS virtual tables reference base-table rows by their rowid values. When transform_sql creates a new table and populates it with INSERT ... SELECT without explicitly copying the rowid, SQLite will allocate new rowid values for the inserted rows. The mapping from FTS rowid -> actual row content is thus broken (FTS still points at old numeric rowids, but the data now lives at different rowids), which explains searches returning wrong rows after table.transform(). Reconfiguring FTS (rebuilding) fixes it because that recreates FTS entries with the new rowids.

Why this candidate is the root cause:
- The transform() API calls transform_sql and executes its SQLs. The transform_sql copy step is precisely where rowids are lost/reassigned: the code performs an INSERT INTO new_table (cols) SELECT old_cols FROM old_table; rather than preserving rowid (for example, INSERT INTO new_table(rowid, cols) SELECT rowid, cols ...). The evidence lines (1920 and 1926) directly show the offending SQL is generated and appended.

Notes on the originally-reported phrasing: the earlier pipeline's description mentioned a CREATE TABLE ... AS SELECT at line 1690. That exact CREATE TABLE ... AS SELECT is present in duplicate() at line 1690, but the transform path does not use duplicate(); transform() uses transform_sql which issues an INSERT ... SELECT (lines ~1914-1926). Both approaches would reassign rowids, but the transform() path's explicit INSERT ... SELECT at 1920 is the one exercised by table.transform() and is the actionable root cause.

No competing candidates were provided. I therefore mark the root cause as the INSERT-copy in transform_sql (sqlite-utils/sqlite_utils/db.py at line 1920).

Suggested fix (not applied here): when copying data for a table that may be referenced by FTS, preserve rowid by including it explicitly in the INSERT/SELECT (INSERT INTO new_table(rowid, col1,...) SELECT rowid, col1,... FROM old_table), or detect and rebuild any dependent FTS tables as part of transform.

--repo is not a git repository; patch.diff is empty and changed_files is unavailable
