### ISSUE TITLE
importing CSV to SQLite as library

### ISSUE THREAD

**Issue by witeshadow** [simonw/sqlite-utils#61]
CSV can be imported to SQLite when used CLI, but I don't see documentation for when using as library.

**Comment by amjith** [comment]
@witeshadow The library version doesn't have helpers around CSV (at least not from what I can see in the code). 

But here's a snippet that makes it easy to insert from CSV using the library. 

```
import csv

# CSV Reader

csv_file = open("filename.csv")   # open the csv file.
reader = csv.reader(csv_file)  # Create a CSV reader
headers = next(reader)   # First line is the header
docs = (dict(zip(headers, row)) for row in reader)

# Now you can use the `sqlite_utils` library. 

db = Database("my_database.db")
db["table_name"].insert_all(docs)
```

This snippet is adapted from reading the CLI source code on how it implements the csv option.

**Comment by simonw** [comment]
Yeah I've thought about this a bit and I'm OK leaving it out.

The core idea of `sqlite-utils` is that if you can create a list, iterator or generator of Python dictionaries you can efficiently insert those into a SQLite table.

The `--csv` function is actually implemented as just a few lines of code which turn that incoming CSV into a generator of dictionaries:

https://github.com/simonw/sqlite-utils/blob/169ea455fc1f1d5e5b6e44cb339ba7ffa9d49c31/sqlite_utils/cli.py#L364-L368

I could turn this into a reusable helper function but since it wouldn't have anything to do with database inserts (it would just be a helper that turns a CSV into a generator of dictionaries) it doesn't feel like it fits well in the Python library section of this package.
