### ISSUE TITLE
order_by mechanism

### ISSUE THREAD

**Issue by metab0t** [simonw/sqlite-utils#76]
In some cases, I want to iterate rows in a table  with `ORDER BY` clause. It would be nice to have a `rows_order_by` function similar to `rows_where`.
In a more general case, `rows_filter` function might be added to allow more customized filtering to iterate rows.

**Comment by simonw** [comment]
I think a neat way to do this would be with an optional argument for `.rows_where()`:

```python
rows = db["table"].rows_where("age > 10", order_by="age desc")
```

If you want everything you can use this:

```python
rows = db["table"].rows_where(order_by="age desc")
```

It's a tiny bit weird calling `.rows_where()` without a where clause, but I think it makes sense here - especially since `.rows` is a property that can't take any arguments - though under the hood it actually does this:

https://github.com/simonw/sqlite-utils/blob/ad6ac19470a67867b96cb4c086450b8e4e46bf02/sqlite_utils/db.py#L436-L443

**Comment by simonw** [comment]
Released in 2.6

**Comment by simonw** [comment]
Documentation here: https://sqlite-utils.readthedocs.io/en/stable/python-api.html#listing-rows

**Comment by metab0t** [comment]
Thanks for your hard work!
